version: "3.7"

services:
  microbin-primary:
    image: microbin-litefs:latest
    container_name: microbin-primary
    hostname: microbin-primary
    ports:
      - "8080:8080"
      - "20202:20202"
    environment:
      - MICROBIN_SQLITE_DB=/litefs/database.sqlite
      - PRIMARY_URL=http://microbin-primary:20202
      - IS_PRIMARY=true
    volumes:
      - ./microbin-data:/microbin_data
      - ./litefs.static-lease.yml:/etc/litefs.yml
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"

  microbin-replica:
    image: microbin-litefs:latest
    container_name: microbin-replica
    hostname: microbin-replica
    ports:
      - "8081:8080"
    environment:
      - MICROBIN_SQLITE_DB=/litefs/database.sqlite
      - PRIMARY_URL=http://microbin-primary:20202
      - IS_PRIMARY=false
    volumes:
      - ./microbin-data:/microbin_data
      - ./litefs.static-lease.yml:/etc/litefs.yml
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    depends_on:
      - microbin-primary
