---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microbin-config
  namespace: default
data:
  TZ: "Asia/Ho_Chi_Minh"
  MICROBIN_ADMIN_USERNAME: "admin"
  MICROBIN_ADMIN_PASSWORD: "UIT@nt531"
  MICROBIN_DISABLE_TELEMETRY: "true"
  MICROBIN_DISABLE_UPDATE_CHECKING: "true"
  MICROBIN_EDITABLE: "true"
  MICROBIN_ENABLE_BURN_AFTER: "true"
  MICROBIN_ENABLE_READONLY: "true"
  MICROBIN_ETERNAL_PASTA: "true"
  MICROBIN_FOOTER_TEXT: "Multi Tenant SQLite Replication in K8s - Group 3 - NT531"
  MICROBIN_HASH_IDS: "true"
  MICROBIN_HELP: "true"
  MICROBIN_HIDE_FOOTER: "false"
  MICROBIN_HIDE_HEADER: "false"
  MICROBIN_HIDE_LOGO: "false"
  MICROBIN_HIGHLIGHTSYNTAX: "true"
  MICROBIN_LIST_SERVER: "false"
  MICROBIN_NO_FILE_UPLOAD: "false"
  MICROBIN_NO_LISTING: "false"
  MICROBIN_PORT: "8080"
  MICROBIN_PRIVATE: "true"
  MICROBIN_QR: "true"
  MICROBIN_READONLY: "false"
  MICROBIN_SHOW_READ_STATS: "true"
  MICROBIN_SQLITE_DB: "/litefs/database.sqlite"
  MICROBIN_THREADS: "1"
  MICROBIN_TITLE: "Multi Tenant (Group 3 - NT531)"
