version:  '3.5'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    container_name: es-container
    environment:
      - discovery.type=single-node
    networks:
      - elastic-network
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.25
    container_name: ls-container
    ports:
      - "5044:5044"
    volumes:
      - "./logstash/config:/usr/share/logstash/config"

  kibana:
    image: docker.elasticsearch.co/kibana/kibana:7.17.25
    container_name: kb-container
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  microbin:
    image:  danielszabo99/microbin:latest
    container_name: microbin
    restart:  unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MICROBIN_ADMIN_USERNAME=admin
      - MICROBIN_ADMIN_PASSWORD=UIT@nt531
      - MICROBIN_HIGHLIGHTSYNTAX=true
      - MICROBIN_HASH_IDS=true
      - MICROBIN_EDITABLE=true
      - MICROBIN_PRIVATE=false
      - MICROBIN_HIDE_FOOTER=true
      - MICROBIN_HELP=true
      - MICROBIN_HIDE_HEADER=true
      - MICROBIN_HIDE_LOGO=false
      - MICROBIN_NO_ETERNAL_PASTA=true
      - MICROBIN_NO_FILE_UPLOAD=false
      - MICROBIN_NO_LISTING=true
      - MICROBIN_THREADS=1
      - MICROBIN_TITLE=nt531-microbin
      - MICROBIN_QR=true
    ports:
      - 8080:8080
    volumes:
      - ./microbin-data:/app/pasta_data
  
  sniper:
    build:
      context: ./sniper
      dockerfile: Dockerfile
    container_name: sniper
    depends_on:
      - microbin
    entrypoint: ["sh", "-c", "sniper -u http://microbin:8080 -n 1000 -c 100 | python3 /app/convertToJson.py > /output/results.json"]
    volumes:
      - ./output:/output
      - ./convertToJson.py:/app/convertToJson.py

networks:
  elastic-network:
    driver: bridge
